### ISSUE TITLE
Editing the notfication section in uservar.py throws an error and makes wizard unusable[Bug]

### ISSUE THREAD

**Issue by SOOTTV** [a4k-openproject/plugin.program.openwizard#41] opened 2019-10-04 18:07 UTC
**Describe the bug**
In uservar.py edit the notify section. Add a URL and change HEADER MESSAGE and then try to use the wizard

**To Reproduce**
1. In uservar.py edit the notify section.
2. Add a URL into 'NOTFICATION = '
3. Edit 'HEADERMESSAGE = '
4. Open wizard
5. Dismiss notification
6. Back out and reopen wizard
7. See error

**Expected behavior**
No error

**Screenshots**

**Platform**
Linux, MacOS, Android

**Additional context**

**Comment by drinfernoo** [comment] 2019-11-12 01:13
Is this on the master or rewrite branch?

**Comment by Tribalize** [comment] 2019-11-16 12:15
tested today on rewrite branch
![amtermath error](https://user-images.githubusercontent.com/6483215/68992999-daccb780-0840-11ea-9cfc-29359bb00395.png)

**Comment by drinfernoo** [comment] 2019-11-16 21:13
@Tribalize Have you set a URL to notifications.txt in uservar.py? Also, as of today, all current code is on the master branch.

**Comment by Tribalize** [comment] 2019-11-17 13:42
tested this morning with master branch. 
In uservar.py i had used https://host/notify.txt and received error on image 1
![amtermath error](https://user-images.githubusercontent.com/6483215/69008209-04a3de00-0916-11ea-8550-c23eaeadbd06.png)

Next i tried https://host/ notifications.txt and received next error. but wizard was usable
![aftermath error 2](https://user-images.githubusercontent.com/6483215/69008231-3cab2100-0916-11ea-9833-11d292805a1d.png)

**Comment by drinfernoo** [comment] 2019-11-17 14:08
I'm unable to reproduce this with a properly formed notify.txt , so I suspect that's your issue.

**Comment by drinfernoo** [comment] 2019-11-21 13:55
This should be fixed as of 3279e6d1810af083ebc810751e33ab0e0b8818f9.

**Closed as completed by drinfernoo** 2019-11-21 13:55 UTC
Labels: bug
